[package]
name = "lldb"
version = "0.0.1"
authors = ["Bruce Mitchener <bruce.mitchener@gmail.com>"]
license = "MIT/Apache-2.0"
readme = "README.md"
description = ""
keywords = ["lldb", "debugger"]
documentation = "https://endoli.github.io/lldb.rs/"
homepage = "https://github.com/endoli/lldb.rs"
repository = "https://github.com/endoli/lldb.rs"
build = "build.rs"

[dependencies]
lldb-sys = "0.0.3"
