[package]
name = "lldb"
version = "0.0.4"
authors = ["Bruce Mitchener <bruce.mitchener@gmail.com>"]
license = "MIT/Apache-2.0"
readme = "README.md"
description = "Rust-like bindings to the public LLDB API. LLDB is the debugger from the LLVM project and is the system debugger on Mac OS X."
keywords = ["lldb", "debugger"]
documentation = "https://endoli.github.io/lldb.rs/"
homepage = "https://github.com/endoli/lldb.rs"
repository = "https://github.com/endoli/lldb.rs"
build = "build.rs"

[[example]]
name = "basic_synchronous"

[dependencies]
lldb-sys = "0.0.10"
